/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Screen;

import Aplication.ModeloTelaPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno
 */
public class CadastroOferta extends javax.swing.JFrame {

    /**
     * Creates new form CadastroOferta
     */
    public CadastroOferta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTituloOferta = new javax.swing.JTextField();
        txtPreço = new javax.swing.JTextField();
        txtCupom = new javax.swing.JTextField();
        txtInformacaoAdicional = new javax.swing.JTextField();
        btnEnviarOferta = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTituloOferta.setBackground(new java.awt.Color(68, 68, 68));
        txtTituloOferta.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        txtTituloOferta.setForeground(new java.awt.Color(255, 255, 255));
        txtTituloOferta.setBorder(null);
        txtTituloOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloOfertaActionPerformed(evt);
            }
        });
        getContentPane().add(txtTituloOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 500, 50));

        txtPreço.setBackground(new java.awt.Color(68, 68, 68));
        txtPreço.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        txtPreço.setForeground(new java.awt.Color(255, 255, 255));
        txtPreço.setBorder(null);
        txtPreço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPreçoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPreço, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 410, 50));

        txtCupom.setBackground(new java.awt.Color(68, 68, 68));
        txtCupom.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        txtCupom.setForeground(new java.awt.Color(255, 255, 255));
        txtCupom.setBorder(null);
        txtCupom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCupomActionPerformed(evt);
            }
        });
        getContentPane().add(txtCupom, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 640, 410, 50));

        txtInformacaoAdicional.setBackground(new java.awt.Color(68, 68, 68));
        txtInformacaoAdicional.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        txtInformacaoAdicional.setForeground(new java.awt.Color(255, 255, 255));
        txtInformacaoAdicional.setActionCommand("<Not Set>");
        txtInformacaoAdicional.setBorder(null);
        txtInformacaoAdicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInformacaoAdicionalActionPerformed(evt);
            }
        });
        getContentPane().add(txtInformacaoAdicional, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 760, 490, 100));

        btnEnviarOferta.setContentAreaFilled(false);
        btnEnviarOferta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviarOferta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarOfertaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviarOferta, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 900, 180, 50));

        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 910, 60, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cadastro de oferta.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 980));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloOfertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloOfertaActionPerformed

    private void txtPreçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPreçoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPreçoActionPerformed

    private void txtCupomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCupomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCupomActionPerformed

    private void txtInformacaoAdicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInformacaoAdicionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInformacaoAdicionalActionPerformed

    private void btnEnviarOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarOfertaActionPerformed
        if (!txtTituloOferta.getText().isEmpty() && !txtPreço.getText().isEmpty()) {
            ModeloTelaPrincipal model = new ModeloTelaPrincipal();
            model.setTituloOferta(txtTituloOferta.getText());
            Principal pcp = new Principal();
            pcp.recebeTituloOferta(model);
            pcp.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Cadastro Incompleto");
        }
    }//GEN-LAST:event_btnEnviarOfertaActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        Principal pcp = new Principal();
        pcp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroOferta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarOferta;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCupom;
    private javax.swing.JTextField txtInformacaoAdicional;
    private javax.swing.JTextField txtPreço;
    private javax.swing.JTextField txtTituloOferta;
    // End of variables declaration//GEN-END:variables
}
